# Generated by Django 3.1.7 on 2021-04-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
